ZERO_DIVISION_MESSAGE = "Division by zero is not possible !!"
NUMBER_SPACE_ERROR = "Number contains space, it should not contain space!"
INPUT_EMPTY_ERROR = "Input cannot be empty"
MORE_NUMBER_ERROR = "Number has more than one digit"
MULTIPLE_OPERATOR_ERROR = "Input has more than one operator"
INVALID_INPUT = "The input is invalid"